let questions = {
  questions: [
    "Who is most likely to arrive late to a meeting?",
    "Who is most likely to organize office events?",
    "Who is most likely to bring homemade treats to share with the team?",
    "Who is most likely to forget their lunch at home?",
    "Who is most likely to be caught singing at their desk?",
    "Who is most likely to volunteer for overtime?",
    "Who is most likely to win an employee of the month award?",
    "Who is most likely to initiate team-building activities?",
    "Who is most likely to have the messiest desk?",
    "Who is most likely to come up with creative solutions in a crisis?",
    "Who is most likely to be the office prankster?",
    "Who is most likely to take charge during a group project?",
    "Who is most likely to spend the most time in the break room?",
    "Who is most likely to start a fitness challenge in the office?",
    "Who is most likely to bring in motivational quotes for the team?",
    "Who is most likely to be the office fashionista?",
    "Who is most likely to take the longest lunch break?",
    "Who is most likely to forget their computer password?",
    "Who is most likely to organize a surprise birthday party for a colleague?",
    "Who is most likely to win in an office trivia competition?",
    "Who is most likely to binge-watch a TV series during work hours?",
    "Who is most likely to be the go-to person for tech support?",
    "Who is most likely to suggest a new office layout?",
    "Who is most likely to fall asleep during a presentation?",
    "Who is most likely to bring in healthy snacks for the team?",
    "Who is most likely to start a book club at work?",
    "Who is most likely to lead a fitness class during breaks?",
    "Who is most likely to be caught gossiping in the office?",
    "Who is most likely to decorate their desk with personal items?",
    "Who is most likely to be the office DJ for team events?",
    "Who is most likely to take the lead in a client presentation?",
    "Who is most likely to organize team outings?",
    "Who is most likely to have the cleanest desk?",
    "Who is most likely to bring in a pet to the office?",
    "Who is most likely to suggest a new office tradition?",
    "Who is most likely to forget about a scheduled meeting?",
    "Who is most likely to excel in multitasking?",
    "Who is most likely to be the office comedian?",
    "Who is most likely to initiate a mentorship program?",
    "Who is most likely to win the company's annual talent show?",
    "Who is most likely to forget a colleague's name?",
    "Who is most likely to suggest a new office policy?",
    "Who is most likely to be the office mediator during conflicts?",
    "Who is most likely to have the best work-life balance?",
    "Who is most likely to win a costume contest during a themed work event?",
    "Who is most likely to forget where they left their phone?",
    "Who is most likely to bring in snacks for the entire team?",
    "Who is most likely to start a new trend in office fashion?",
    "Who is most likely to be the first to respond to emails?",
    "Who is most likely to participate in a charity run?",
    "Who is most likely to have the most organized inbox?",
    "Who is most likely to bring in a homemade lunch every day?",
    "Who is most likely to lead a team-building retreat?",
    'Who is most likely to win a "Best Dressed" award at a company event?',
    "Who is most likely to organize a team-building escape room experience?",
    "Who is most likely to forget to mute themselves during a virtual meeting?",
    'Who is most likely to be the office "tech guru"?',
    "Who is most likely to suggest a new team-building exercise?",
    "Who is most likely to take on the role of team motivator?",
    "Who is most likely to be the office fashion police?",
    "Who is most likely to bring in a plant to brighten up the office?",
    "Who is most likely to forget their work anniversary?",
    "Who is most likely to start a company podcast?",
    "Who is most likely to organize a themed dress-up day?",
    "Who is most likely to initiate a mentorship program in the company?",
    "Who is most likely to organize a team-building cooking class?",
    "Who is most likely to forget to turn off the office coffee machine?",
    "Who is most likely to be the office trendsetter?",
    "Who is most likely to start a weekly team newsletter?",
    "Who is most likely to bring in a surprise treat for the team?",
    "Who is most likely to mix up important files on their desk?",
    "Who is most likely to organize a team-building improv workshop?",
    "Who is most likely to have a secret talent no one knows about?",
    "Who is most likely to suggest a new office gadget everyone needs?",
    "Who is most likely to forget about a colleague's birthday?",
    "Who is most likely to lead a company-wide volunteer day?",
    "Who is most likely to bring in a homemade dessert for a team celebration?",
    "Who is most likely to organize a team-building board game night?",
    "Who is most likely to forget their headphones at home?",
    'Who is most likely to win the title of "Most Adventurous Employee"?',
    "Who is most likely to suggest a new office policy on remote work?",
    "Who is most likely to bring in a surprise guest speaker for a team meeting?",
    "Who is most likely to suggest a new team-building location?",
    "Who is most likely to have a collection of funny office-themed memes?",
    "Who is most likely to forget about a scheduled training session?",
    "Who is most likely to win the office ping pong tournament?",
    "Who is most likely to initiate a company-wide green initiative?",
    "Who is most likely to forget to submit their timesheet on time?",
    "Who is most likely to suggest a new team-building challenge involving technology?",
    "Who is most likely to be caught talking to themselves at their desk?",
    "Who is most likely to forget their company ID badge?",
    "Who is most likely to bring in a motivational speaker for the team?",
    'Who is most likely to win the title of "Most Tech-Savvy Employee"?',
    "Who is most likely to suggest a new office seating arrangement?",
    "Who is most likely to organize a team-building puzzle-solving day?",
    "Who is most likely to have the best office-themed Zoom background?",
    "Who is most likely to forget to charge their work laptop overnight?",
    "Who is most likely to start a company-wide initiative for eco-friendly practices?",
    "Who is most likely to win the office talent show for the third year in a row?",
    "Who is most likely to bring in a surprise team-building activity for a Monday morning?",
    "Who is most likely to initiate a company-wide initiative for employee well-being?",
    "Who is most likely to forget about a team-building offsite?",
    "Who is most likely to suggest a team-building day at a virtual reality painting class?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
  ],
};

module.exports = {
  questions,
};
