export const content = {
  game: "game",
  people: "your friends",
  trophy: "🏆",
  avatars: {
    devil: "😈",
    robot: "🤖",
    alien: "👽",
    ghost: "👻",
    clown: "🤡",
    nerd: "🤓",
    angel: "😇",
    unicorn: "🦄",
    chick: "🐣",
    dolphin: "🐳",
    snake: "🐍",
    teddy: "🧸",
    work: "👔",
    nsfw: "🚫",
    cat: "🐱",
    dog: "🐶",
    panda: "🐼",
    fox: "🦊",
    koala: "🐨",
    bear: "🐻",
    star: "⭐",
    heart: "❤️",
    wizard: "🧙‍♂️",
    ninja: "🥷",
    superhero: "🦸‍♀️",
    vampire: "🧛‍♂️",
  },
  colors: ["blue", "purple", "pink", "orange", "green", "yellow"],
};
